apiVersion: apps/v1
kind: Deployment
metadata:
  name: polardb-order-deployment
  labels:
    db: polardb-order
spec:
  replicas: 1
  selector:
    matchLabels:
      db: polardb-order
  template:
    metadata:
      labels:
        db: polardb-order
    spec:
      containers:
      - name: polardb-order
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: polardb_order
