apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: thomasvitale/order-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 9002
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://polardb-order-service:5432/polardb_order
