apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
spec:
  type: NodePort
  selector:
    app: dispatcher-service
  ports:
  - port: 9003
    targetPort: 9003
    nodePort: 30003
