server:
  port: 9001
  tomcat:
    accept-count: 100
    connection-timeout: 2000
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10

spring:
  datasource:
    username: user_catalog
    password: user_password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      pool-name: polardb-pool
  jpa:
    hibernate:
      ddl-auto: validate
