apiVersion: v1
kind: Service
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  type: NodePort
  selector:
    app: edge-service
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30000
